{% set name = "prophet" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e682e8ea6e1ee26a92cf289f207d539f30e44879126c128ff8f4e360eb25a8b

build:
  number: 1
  # As of 3/4/2022, we don't have the deps built out to support a py310 build.
  skip: True  # [py==310]
  # 2022/9/5: Currently pystan~=2.19.1.1 isn't available on s390x
  skip: True  # [s390x]
  script: 
    - {{ PYTHON }} -m pip install . -vv
  binary_has_prefix_files:
    - {{ SP_DIR|replace("\\", "/") }}/stan_model/prophet_model.pkl

requirements:
  build:
    - {{ compiler('cxx') }}  # [win]
  host:
    - python
    - pip
    # Explanation:
    #
    # setup.py imports fbprophet.models.StanBackendEnum, triggering
    # fbprophet/__init__.py and thus making the runtime dependencies
    # also build-time dependencies.
    #
    # These requirements are copied from python/requirements.txt
    - cython >=0.22
    - pystan ~=2.19.1.1
    - numpy >=1.15.4
    - pandas >=1.0.4
    - matplotlib-base >=2.0.0
    - LunarCalendar >=0.0.9
    - convertdate >=2.1.2
    - holidays >=0.10.2
    - setuptools <60
    - setuptools-git >=1.2
    - python-dateutil >=2.8.0
    - tqdm >=4.36.1
  run:
    - python
    - cython >=0.22
    - pystan ~=2.19.1.1
    - pandas >=1.0.4
    - matplotlib-base >=2.0.0
    - LunarCalendar >=0.0.9
    - convertdate >=2.1.2
    - holidays >=0.10.2
    - setuptools-git >=1.2
    - python-dateutil >=2.8.0
    - tqdm >=4.36.1
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - prophet
    - prophet.tests
  commands:
    - echo "Running 'file'" && file {{ SP_DIR|replace("\\", "/") }}/stan_model/prophet_model.pkl || true  # [osx]
    - echo "Running 'ldid'" && ldid -S {{ SP_DIR|replace("\\", "/") }}/stan_model/prophet_model.pkl || true  # [osx]
    # 3/4/2022: Turning off 'pip check' because the requirements.txt
    # lists 'cmdstanpy' which is an experimental backend that we are
    # not supporting at this time.
    #- pip check
    - py.test -v --pyargs prophet
  requires:
    - pip
    - pytest
    # 2022/9/5: To fix an error "Importing plotly failed. Interactive plots will not work":
    - ipywidgets
    - notebook
    - plotly >=4.0

about:
  home: https://facebook.github.io/prophet/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic Forecasting Procedure
  description: |
    Implements a procedure for forecasting time series data based on an
    additive model where non-linear trends are fit with yearly, weekly, and
    daily seasonality, plus holiday effects. It works best with time series
    that have strong seasonal effects and several seasons of historical data.
    Prophet is robust to missing data and shifts in the trend, and typically
    handles outliers well.
  doc_url: https://facebook.github.io/prophet/docs/quick_start.html
  dev_url: https://github.com/facebook/prophet

extra:
  recipe-maintainers:
    - bletham
    - maresb
