{% set name = "prophet" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3cfb7665962e983b05367f65f37692d9c8569a86335f3f163925ec89a128bfab

build:
  number: 0
  skip: true  # [py<37 or py>=310]
  # Currently pystan~=2.19.1.1 isn't available on s390x
  skip: True  # [s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  binary_has_prefix_files:
    - {{ SP_DIR|replace("\\", "/") }}/stan_model/prophet_model.pkl

requirements:
  host:
    - python
    - cython 0.29.33
    - numpy {{ numpy }}
    - pip
    - pystan 2.19.1.1
    - setuptools
    - wheel
  run:
    - python
    - pystan ~=2.19.1.1
    - pandas >=1.0.4
    - matplotlib-base >=2.0.0
    - LunarCalendar >=0.0.9
    - convertdate >=2.1.2
    - holidays >=0.14.2
    - python-dateutil >=2.8.0
    - tqdm >=4.36.1
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - prophet
    - prophet.tests
  requires:
    - pip
    - pytest
    # 3/4/2022: Turning off 'pip check' because the requirements.txt
    # lists 'cmdstanpy' which is an experimental backend that we are
    # not supporting at this time.
    #- pip check
    # 2022/9/5: To fix an error "Importing plotly failed. Interactive plots will not work":
    - ipywidgets
    - notebook
    - plotly >=4.0

about:
  home: https://facebook.github.io/prophet/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic Forecasting Procedure
  description: |
    Implements a procedure for forecasting time series data based on an
    additive model where non-linear trends are fit with yearly, weekly, and
    daily seasonality, plus holiday effects. It works best with time series
    that have strong seasonal effects and several seasons of historical data.
    Prophet is robust to missing data and shifts in the trend, and typically
    handles outliers well.
  doc_url: https://facebook.github.io/prophet/docs/quick_start.html
  dev_url: https://github.com/facebook/prophet

extra:
  recipe-maintainers:
    - bletham
    - maresb
